"""Add soft delete columns to documents

Revision ID: 727927e18a22
Revises: b2e49f5ee987
Create Date: 2026-04-03 01:54:36.390882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727927e18a22'
down_revision: Union[str, None] = 'b2e49f5ee987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_foreign_key('fk_documents_deleted_by_id', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_deleted_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_deleted_at'))
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
